/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'name' : string,
  'isActive' : boolean,
}
export type CategoryId = bigint;
export interface Comment {
  'id' : CommentId,
  'upvotes' : bigint,
  'content' : string,
  'isHidden' : boolean,
  'timestamp' : bigint,
  'ipHash' : IpHash,
  'postId' : PostId,
}
export type CommentId = bigint;
export type CreateCommentError = { 'bannedIp' : null } |
  { 'internalError' : null } |
  { 'contentBlocked' : null };
export type CreatePostError = { 'rateLimitExceeded' : null } |
  { 'bannedIp' : null } |
  { 'internalError' : null } |
  { 'contentBlocked' : null };
export type IpHash = string;
export interface Post {
  'id' : PostId,
  'upvotes' : bigint,
  'title' : string,
  'content' : string,
  'isHidden' : boolean,
  'timestamp' : bigint,
  'ipHash' : IpHash,
  'commentCount' : bigint,
  'category' : [] | [CategoryId],
}
export type PostId = bigint;
export type PostTab = { 'latest' : null } |
  { 'trending' : null };
export interface PostWithComments { 'post' : Post, 'comments' : Array<Comment> }
export interface PostsPage { 'totalCount' : bigint, 'posts' : Array<Post> }
export interface Stats {
  'dailyPostCounts' : Array<bigint>,
  'totalPosts' : bigint,
  'totalComments' : bigint,
}
export interface UpvoteResult { 'alreadyVoted' : boolean, 'newCount' : bigint }
export interface _SERVICE {
  'adminAddBlockedKeyword' : ActorMethod<[string, string], boolean>,
  'adminAddCategory' : ActorMethod<[string, string], boolean>,
  'adminBanIp' : ActorMethod<[IpHash, string], boolean>,
  'adminDeleteComment' : ActorMethod<[CommentId, string], boolean>,
  'adminDeletePost' : ActorMethod<[PostId, string], boolean>,
  'adminGetBannedIps' : ActorMethod<[string], [] | [Array<IpHash>]>,
  'adminGetBlockedKeywords' : ActorMethod<[string], [] | [Array<string>]>,
  'adminGetCategories' : ActorMethod<[string], [] | [Array<Category>]>,
  'adminRemoveBlockedKeyword' : ActorMethod<[string, string], boolean>,
  'adminRemoveCategory' : ActorMethod<[CategoryId, string], boolean>,
  'adminUnbanIp' : ActorMethod<[IpHash, string], boolean>,
  'createComment' : ActorMethod<
    [PostId, string, IpHash],
    { 'ok' : Comment } |
      { 'err' : CreateCommentError }
  >,
  'createPost' : ActorMethod<
    [string, string, [] | [CategoryId], IpHash],
    { 'ok' : Post } |
      { 'err' : CreatePostError }
  >,
  'getAnonymousId' : ActorMethod<[IpHash, PostId], bigint>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getPost' : ActorMethod<[PostId], PostWithComments>,
  'getPosts' : ActorMethod<
    [PostTab, [] | [CategoryId], bigint, bigint],
    PostsPage
  >,
  'getStats' : ActorMethod<[], Stats>,
  'upvoteComment' : ActorMethod<[CommentId, IpHash], [] | [UpvoteResult]>,
  'upvotePost' : ActorMethod<[PostId, IpHash], [] | [UpvoteResult]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];