/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IpHash = IDL.Text;
export const CommentId = IDL.Nat;
export const PostId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'upvotes' : IDL.Nat,
  'content' : IDL.Text,
  'isHidden' : IDL.Bool,
  'timestamp' : IDL.Int,
  'ipHash' : IpHash,
  'postId' : PostId,
});
export const CreateCommentError = IDL.Variant({
  'bannedIp' : IDL.Null,
  'internalError' : IDL.Null,
  'contentBlocked' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : PostId,
  'upvotes' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isHidden' : IDL.Bool,
  'timestamp' : IDL.Int,
  'ipHash' : IpHash,
  'commentCount' : IDL.Nat,
  'category' : IDL.Opt(CategoryId),
});
export const CreatePostError = IDL.Variant({
  'rateLimitExceeded' : IDL.Null,
  'bannedIp' : IDL.Null,
  'internalError' : IDL.Null,
  'contentBlocked' : IDL.Null,
});
export const PostWithComments = IDL.Record({
  'post' : Post,
  'comments' : IDL.Vec(Comment),
});
export const PostTab = IDL.Variant({
  'latest' : IDL.Null,
  'trending' : IDL.Null,
});
export const PostsPage = IDL.Record({
  'totalCount' : IDL.Nat,
  'posts' : IDL.Vec(Post),
});
export const Stats = IDL.Record({
  'dailyPostCounts' : IDL.Vec(IDL.Nat),
  'totalPosts' : IDL.Nat,
  'totalComments' : IDL.Nat,
});
export const UpvoteResult = IDL.Record({
  'alreadyVoted' : IDL.Bool,
  'newCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'adminAddBlockedKeyword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminAddCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminBanIp' : IDL.Func([IpHash, IDL.Text], [IDL.Bool], []),
  'adminDeleteComment' : IDL.Func([CommentId, IDL.Text], [IDL.Bool], []),
  'adminDeletePost' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
  'adminGetBannedIps' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IpHash))],
      ['query'],
    ),
  'adminGetBlockedKeywords' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'adminGetCategories' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Category))],
      ['query'],
    ),
  'adminRemoveBlockedKeyword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminRemoveCategory' : IDL.Func([CategoryId, IDL.Text], [IDL.Bool], []),
  'adminUnbanIp' : IDL.Func([IpHash, IDL.Text], [IDL.Bool], []),
  'createComment' : IDL.Func(
      [PostId, IDL.Text, IpHash],
      [IDL.Variant({ 'ok' : Comment, 'err' : CreateCommentError })],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(CategoryId), IpHash],
      [IDL.Variant({ 'ok' : Post, 'err' : CreatePostError })],
      [],
    ),
  'getAnonymousId' : IDL.Func([IpHash, PostId], [IDL.Nat], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getPost' : IDL.Func([PostId], [PostWithComments], ['query']),
  'getPosts' : IDL.Func(
      [PostTab, IDL.Opt(CategoryId), IDL.Nat, IDL.Nat],
      [PostsPage],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'upvoteComment' : IDL.Func([CommentId, IpHash], [IDL.Opt(UpvoteResult)], []),
  'upvotePost' : IDL.Func([PostId, IpHash], [IDL.Opt(UpvoteResult)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IpHash = IDL.Text;
  const CommentId = IDL.Nat;
  const PostId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'upvotes' : IDL.Nat,
    'content' : IDL.Text,
    'isHidden' : IDL.Bool,
    'timestamp' : IDL.Int,
    'ipHash' : IpHash,
    'postId' : PostId,
  });
  const CreateCommentError = IDL.Variant({
    'bannedIp' : IDL.Null,
    'internalError' : IDL.Null,
    'contentBlocked' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'upvotes' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isHidden' : IDL.Bool,
    'timestamp' : IDL.Int,
    'ipHash' : IpHash,
    'commentCount' : IDL.Nat,
    'category' : IDL.Opt(CategoryId),
  });
  const CreatePostError = IDL.Variant({
    'rateLimitExceeded' : IDL.Null,
    'bannedIp' : IDL.Null,
    'internalError' : IDL.Null,
    'contentBlocked' : IDL.Null,
  });
  const PostWithComments = IDL.Record({
    'post' : Post,
    'comments' : IDL.Vec(Comment),
  });
  const PostTab = IDL.Variant({ 'latest' : IDL.Null, 'trending' : IDL.Null });
  const PostsPage = IDL.Record({
    'totalCount' : IDL.Nat,
    'posts' : IDL.Vec(Post),
  });
  const Stats = IDL.Record({
    'dailyPostCounts' : IDL.Vec(IDL.Nat),
    'totalPosts' : IDL.Nat,
    'totalComments' : IDL.Nat,
  });
  const UpvoteResult = IDL.Record({
    'alreadyVoted' : IDL.Bool,
    'newCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'adminAddBlockedKeyword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminAddCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminBanIp' : IDL.Func([IpHash, IDL.Text], [IDL.Bool], []),
    'adminDeleteComment' : IDL.Func([CommentId, IDL.Text], [IDL.Bool], []),
    'adminDeletePost' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
    'adminGetBannedIps' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IpHash))],
        ['query'],
      ),
    'adminGetBlockedKeywords' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'adminGetCategories' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Category))],
        ['query'],
      ),
    'adminRemoveBlockedKeyword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminRemoveCategory' : IDL.Func([CategoryId, IDL.Text], [IDL.Bool], []),
    'adminUnbanIp' : IDL.Func([IpHash, IDL.Text], [IDL.Bool], []),
    'createComment' : IDL.Func(
        [PostId, IDL.Text, IpHash],
        [IDL.Variant({ 'ok' : Comment, 'err' : CreateCommentError })],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(CategoryId), IpHash],
        [IDL.Variant({ 'ok' : Post, 'err' : CreatePostError })],
        [],
      ),
    'getAnonymousId' : IDL.Func([IpHash, PostId], [IDL.Nat], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getPost' : IDL.Func([PostId], [PostWithComments], ['query']),
    'getPosts' : IDL.Func(
        [PostTab, IDL.Opt(CategoryId), IDL.Nat, IDL.Nat],
        [PostsPage],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'upvoteComment' : IDL.Func(
        [CommentId, IpHash],
        [IDL.Opt(UpvoteResult)],
        [],
      ),
    'upvotePost' : IDL.Func([PostId, IpHash], [IDL.Opt(UpvoteResult)], []),
  });
};

export const init = ({ IDL }) => { return []; };