/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    upvotes: bigint;
    content: string;
    isHidden: boolean;
    timestamp: bigint;
    ipHash: IpHash;
    postId: PostId;
}
export type PostId = bigint;
export interface UpvoteResult {
    alreadyVoted: boolean;
    newCount: bigint;
}
export interface Stats {
    dailyPostCounts: Array<bigint>;
    totalPosts: bigint;
    totalComments: bigint;
}
export type IpHash = string;
export interface PostsPage {
    totalCount: bigint;
    posts: Array<Post>;
}
export interface PostWithComments {
    post: Post;
    comments: Array<Comment>;
}
export interface Post {
    id: PostId;
    upvotes: bigint;
    title: string;
    content: string;
    isHidden: boolean;
    timestamp: bigint;
    ipHash: IpHash;
    commentCount: bigint;
    category?: CategoryId;
}
export type CategoryId = bigint;
export interface Category {
    id: CategoryId;
    name: string;
    isActive: boolean;
}
export enum CreateCommentError {
    bannedIp = "bannedIp",
    internalError = "internalError",
    contentBlocked = "contentBlocked"
}
export enum CreatePostError {
    rateLimitExceeded = "rateLimitExceeded",
    bannedIp = "bannedIp",
    internalError = "internalError",
    contentBlocked = "contentBlocked"
}
export enum PostTab {
    latest = "latest",
    trending = "trending"
}
export interface backendInterface {
    adminAddBlockedKeyword(keyword: string, adminPassword: string): Promise<boolean>;
    adminAddCategory(name: string, adminPassword: string): Promise<boolean>;
    adminBanIp(ipHash: IpHash, adminPassword: string): Promise<boolean>;
    adminDeleteComment(id: CommentId, adminPassword: string): Promise<boolean>;
    adminDeletePost(id: PostId, adminPassword: string): Promise<boolean>;
    adminGetBannedIps(adminPassword: string): Promise<Array<IpHash> | null>;
    adminGetBlockedKeywords(adminPassword: string): Promise<Array<string> | null>;
    adminGetCategories(adminPassword: string): Promise<Array<Category> | null>;
    adminRemoveBlockedKeyword(keyword: string, adminPassword: string): Promise<boolean>;
    adminRemoveCategory(id: CategoryId, adminPassword: string): Promise<boolean>;
    adminUnbanIp(ipHash: IpHash, adminPassword: string): Promise<boolean>;
    createComment(postId: PostId, content: string, ipHash: IpHash): Promise<{
        __kind__: "ok";
        ok: Comment;
    } | {
        __kind__: "err";
        err: CreateCommentError;
    }>;
    createPost(title: string, content: string, category: CategoryId | null, ipHash: IpHash): Promise<{
        __kind__: "ok";
        ok: Post;
    } | {
        __kind__: "err";
        err: CreatePostError;
    }>;
    getAnonymousId(ipHash: IpHash, postId: PostId): Promise<bigint>;
    getCategories(): Promise<Array<Category>>;
    getComments(postId: PostId): Promise<Array<Comment>>;
    getPost(id: PostId): Promise<PostWithComments>;
    getPosts(tab: PostTab, category: CategoryId | null, page: bigint, pageSize: bigint): Promise<PostsPage>;
    getStats(): Promise<Stats>;
    upvoteComment(commentId: CommentId, ipHash: IpHash): Promise<UpvoteResult | null>;
    upvotePost(postId: PostId, ipHash: IpHash): Promise<UpvoteResult | null>;
}
import type { Category as _Category, CategoryId as _CategoryId, Comment as _Comment, CreateCommentError as _CreateCommentError, CreatePostError as _CreatePostError, IpHash as _IpHash, Post as _Post, PostId as _PostId, PostTab as _PostTab, PostWithComments as _PostWithComments, PostsPage as _PostsPage, UpvoteResult as _UpvoteResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminAddBlockedKeyword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddBlockedKeyword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddBlockedKeyword(arg0, arg1);
            return result;
        }
    }
    async adminAddCategory(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCategory(arg0, arg1);
            return result;
        }
    }
    async adminBanIp(arg0: IpHash, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBanIp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBanIp(arg0, arg1);
            return result;
        }
    }
    async adminDeleteComment(arg0: CommentId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteComment(arg0, arg1);
            return result;
        }
    }
    async adminDeletePost(arg0: PostId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeletePost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeletePost(arg0, arg1);
            return result;
        }
    }
    async adminGetBannedIps(arg0: string): Promise<Array<IpHash> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetBannedIps(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetBannedIps(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetBlockedKeywords(arg0: string): Promise<Array<string> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetBlockedKeywords(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetBlockedKeywords(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetCategories(arg0: string): Promise<Array<Category> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetCategories(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetCategories(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRemoveBlockedKeyword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveBlockedKeyword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveBlockedKeyword(arg0, arg1);
            return result;
        }
    }
    async adminRemoveCategory(arg0: CategoryId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveCategory(arg0, arg1);
            return result;
        }
    }
    async adminUnbanIp(arg0: IpHash, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnbanIp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnbanIp(arg0, arg1);
            return result;
        }
    }
    async createComment(arg0: PostId, arg1: string, arg2: IpHash): Promise<{
        __kind__: "ok";
        ok: Comment;
    } | {
        __kind__: "err";
        err: CreateCommentError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1, arg2);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1, arg2);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: string, arg2: CategoryId | null, arg3: IpHash): Promise<{
        __kind__: "ok";
        ok: Post;
    } | {
        __kind__: "err";
        err: CreatePostError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnonymousId(arg0: IpHash, arg1: PostId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnonymousId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnonymousId(arg0, arg1);
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getComments(arg0: PostId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getPost(arg0: PostId): Promise<PostWithComments> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_PostWithComments_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_PostWithComments_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(arg0: PostTab, arg1: CategoryId | null, arg2: bigint, arg3: bigint): Promise<PostsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts(to_candid_PostTab_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_PostsPage_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts(to_candid_PostTab_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_PostsPage_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async upvoteComment(arg0: CommentId, arg1: IpHash): Promise<UpvoteResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteComment(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteComment(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async upvotePost(arg0: PostId, arg1: IpHash): Promise<UpvoteResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.upvotePost(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvotePost(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CreateCommentError_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateCommentError): CreateCommentError {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CreatePostError_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatePostError): CreatePostError {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PostWithComments_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostWithComments): PostWithComments {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PostsPage_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostsPage): PostsPage {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_IpHash>]): Array<IpHash> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CategoryId]): CategoryId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UpvoteResult]): UpvoteResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Category>]): Array<Category> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    upvotes: bigint;
    title: string;
    content: string;
    isHidden: boolean;
    timestamp: bigint;
    ipHash: _IpHash;
    commentCount: bigint;
    category: [] | [_CategoryId];
}): {
    id: PostId;
    upvotes: bigint;
    title: string;
    content: string;
    isHidden: boolean;
    timestamp: bigint;
    ipHash: IpHash;
    commentCount: bigint;
    category?: CategoryId;
} {
    return {
        id: value.id,
        upvotes: value.upvotes,
        title: value.title,
        content: value.content,
        isHidden: value.isHidden,
        timestamp: value.timestamp,
        ipHash: value.ipHash,
        commentCount: value.commentCount,
        category: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.category))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    post: _Post;
    comments: Array<_Comment>;
}): {
    post: Post;
    comments: Array<Comment>;
} {
    return {
        post: from_candid_Post_n9(_uploadFile, _downloadFile, value.post),
        comments: value.comments
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    posts: Array<_Post>;
}): {
    totalCount: bigint;
    posts: Array<Post>;
} {
    return {
        totalCount: value.totalCount,
        posts: from_candid_vec_n20(_uploadFile, _downloadFile, value.posts)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rateLimitExceeded: null;
} | {
    bannedIp: null;
} | {
    internalError: null;
} | {
    contentBlocked: null;
}): CreatePostError {
    return "rateLimitExceeded" in value ? CreatePostError.rateLimitExceeded : "bannedIp" in value ? CreatePostError.bannedIp : "internalError" in value ? CreatePostError.internalError : "contentBlocked" in value ? CreatePostError.contentBlocked : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Comment;
} | {
    err: _CreateCommentError;
}): {
    __kind__: "ok";
    ok: Comment;
} | {
    __kind__: "err";
    err: CreateCommentError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_CreateCommentError_n5(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bannedIp: null;
} | {
    internalError: null;
} | {
    contentBlocked: null;
}): CreateCommentError {
    return "bannedIp" in value ? CreateCommentError.bannedIp : "internalError" in value ? CreateCommentError.internalError : "contentBlocked" in value ? CreateCommentError.contentBlocked : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Post;
} | {
    err: _CreatePostError;
}): {
    __kind__: "ok";
    ok: Post;
} | {
    __kind__: "err";
    err: CreatePostError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Post_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_CreatePostError_n12(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n9(_uploadFile, _downloadFile, x));
}
function to_candid_PostTab_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostTab): _PostTab {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryId | null): [] | [_CategoryId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostTab): {
    latest: null;
} | {
    trending: null;
} {
    return value == PostTab.latest ? {
        latest: null
    } : value == PostTab.trending ? {
        trending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
